version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gosec
    - gocyclo
    - misspell
    - revive
    - nolintlint
    - unused

linters-settings:
  gocyclo:
    min-complexity: 15
  gosec:
    excludes:
      - G104
  revive:
    rules:
      - name: exported
        disabled: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
    - path: internal/migrate/
      linters:
        - unused
